services:
  ollama-service:
    image: ollama/ollama:0.1.27
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - ../ollama:/root/.ollama

  download-deepseek-coder-llm:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "${OLLAMA_BASE_URL}/api/pull", "-d", '{"name": "deepseek-coder"}']
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}  
    depends_on:
      ollama-service:
        condition: service_started

  little-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      ollama-service:
        condition: service_started
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    ports:
      - 8501:8501