services:
  little-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      ollama-service:
        condition: service_started
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    # docker compose watch
    develop:
      watch:
        - action: sync
          path: app
          target: app
    ports:
      - 8501:8501
