services:
  ollama-service:
    image: ollama/ollama:0.1.26
    environment:
      #- OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      # Ollama is running in a container without GPU
    volumes:
      - ../ollama:/root/.ollama
    #ports:
    #  - 11435:11435



